In [2]:
from common.optimizer import *
import numpy as np

In [3]:
params = {'x':1, 'y':2}
grad={'x':3, 'y':3}

n = SGD(1/3)

n.update(params,grad)
print(params)

{'x': 0.0, 'y': 1.0}


In [4]:
n2 = Nesterov()

n2.update(params,grad)
print(params)



{'x': -0.0813, 'y': 0.9187000000000001}


In [5]:
n3 = AdaGrad()

n3.update(params, grad)
print(params)

{'x': -0.09129999966666667, 'y': 0.9087000003333334}


In [9]:
n4 = Adam()

n4.update(params,grad)
print(params)

{'x': -0.09529999545030092, 'y': 0.9047000045496993}


In [12]:

x = np.array([1,2,3])
y = np.array([4,5,6])
X, Y = np.meshgrid(x, y)
print(X)
print(Y)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[4 4 4]
 [5 5 5]
 [6 6 6]]
