In [1]:
import sys
sys.path.append('C:/Users/dinle/Code/Learning/Py_Code/AI_Learning/mnist')
sys.path.append('C:/Users/dinle/Code/Learning/Py_Code/AI_Learning/NodeLayer')
import NodeLayer.Layers.layers as layers
import mnist.common.layers as layers2
import numpy as np


scale = np.sqrt(2.0 / 50)
W = scale * np.random.randn(50, 100)
b = np.ones(100)
x = np.random.randn(128, 50)
gamma = np.ones(100)
beta = np.zeros(100)
t = np.random.randint(0,49,128)

L1 = layers.SoftmaxWithLoss()
L2 = layers2.SoftmaxWithLoss()

W

array([[-0.0434, -0.0885,  0.4716, ..., -0.4528,  0.0788,
         0.2606],
       [ 0.2379, -0.1031, -0.1605, ..., -0.1271,  0.1174,
         0.1673],
       [-0.4447, -0.0483,  0.1339, ...,  0.1357, -0.135 ,
         0.1927],
       ...,
       [ 0.0129, -0.0104,  0.4285, ...,  0.0625, -0.1096,
        -0.0316],
       [ 0.0806, -0.1959,  0.1941, ..., -0.0947, -0.126 ,
         0.0434],
       [-0.2215,  0.1016,  0.5185, ..., -0.2471,  0.3631,
        -0.2206]])

In [2]:
def softmax(x):
    if x.ndim == 2:
        x = x.T
        x = x - np.max(x, axis=0)
        y = np.exp(x) / np.sum(np.exp(x), axis=0)
        return y.T

    x = x - np.max(x) # 오버플로 대책
    return np.exp(x) / np.sum(np.exp(x))

In [3]:
def softmax2(x):
    if x.ndim == 2:
        x = x.T
        x = x - np.max(x, axis=0)
        a = np.exp(x)
        b = (1/ np.sum(np.exp(x), axis=0))
        y = a*b
        return y.T

    x = x - np.max(x) # 오버플로 대책
    return np.exp(x) / np.sum(np.exp(x))

In [4]:
f1 = L1.forward(x,t)
f2 = L2.forward(x,t)

In [5]:
s1 = softmax(x)

In [6]:
s2 = softmax2(x)

In [7]:
s1

array([[0.0073, 0.015 , 0.0264, ..., 0.0402, 0.0041,
        0.005 ],
       [0.0024, 0.0319, 0.0024, ..., 0.0026, 0.0478,
        0.0053],
       [0.0169, 0.0068, 0.0007, ..., 0.0554, 0.0028,
        0.0058],
       ...,
       [0.0133, 0.0205, 0.0323, ..., 0.0177, 0.0067,
        0.0155],
       [0.0139, 0.0025, 0.0025, ..., 0.0163, 0.0034,
        0.0107],
       [0.0867, 0.0364, 0.0067, ..., 0.0119, 0.0352,
        0.0038]])

In [8]:
s2

array([[0.0073, 0.015 , 0.0264, ..., 0.0402, 0.0041,
        0.005 ],
       [0.0024, 0.0319, 0.0024, ..., 0.0026, 0.0478,
        0.0053],
       [0.0169, 0.0068, 0.0007, ..., 0.0554, 0.0028,
        0.0058],
       ...,
       [0.0133, 0.0205, 0.0323, ..., 0.0177, 0.0067,
        0.0155],
       [0.0139, 0.0025, 0.0025, ..., 0.0163, 0.0034,
        0.0107],
       [0.0867, 0.0364, 0.0067, ..., 0.0119, 0.0352,
        0.0038]])

In [9]:
np.min(s1/s2)

0.9999999999999998

In [10]:
f1

4.520099200015142

In [11]:
f2

4.520099200015142

In [12]:
ff = f1 - f2
np.max(ff)

0.0

In [13]:
b1 = L1.backward(f1)
b2 = L2.backward(f2)

In [14]:
b1

array([[5.6981e-05, 1.1681e-04, 2.0661e-04, ...,
        3.1374e-04, 3.2343e-05, 3.9228e-05],
       [1.9039e-05, 2.4947e-04, 1.8652e-05, ...,
        2.0447e-05, 3.7353e-04, 4.1322e-05],
       [1.3225e-04, 5.3318e-05, 5.2000e-06, ...,
        4.3249e-04, 2.2033e-05, 4.5270e-05],
       ...,
       [1.0385e-04, 1.6043e-04, 2.5206e-04, ...,
        1.3851e-04, 5.2050e-05, 1.2115e-04],
       [1.0858e-04, 1.9867e-05, 1.9899e-05, ...,
        1.2769e-04, 2.6687e-05, 8.3419e-05],
       [6.7755e-04, 2.8459e-04, 5.2096e-05, ...,
        9.3171e-05, 2.7481e-04, 2.9648e-05]])

In [15]:
b2

array([[5.6985e-05, 1.1681e-04, 2.0662e-04, ...,
        3.1376e-04, 3.2345e-05, 3.9230e-05],
       [1.9040e-05, 2.4949e-04, 1.8654e-05, ...,
        2.0449e-05, 3.7356e-04, 4.1326e-05],
       [1.3225e-04, 5.3318e-05, 5.2000e-06, ...,
        4.3249e-04, 2.2034e-05, 4.5271e-05],
       ...,
       [1.0385e-04, 1.6043e-04, 2.5206e-04, ...,
        1.3851e-04, 5.2050e-05, 1.2116e-04],
       [1.0859e-04, 1.9868e-05, 1.9900e-05, ...,
        1.2770e-04, 2.6688e-05, 8.3424e-05],
       [6.7756e-04, 2.8459e-04, 5.2097e-05, ...,
        9.3173e-05, 2.7481e-04, 2.9648e-05]])

In [16]:
bb = b1-b2
np.max(bb)

9.90034350755939e-07

In [17]:
# dw = L1.dW - L2.dW
# np.max(dw)

In [18]:
y1 = L1.y
y2 = L2.y

In [19]:
y1

array([[0.0073, 0.015 , 0.0264, ..., 0.0402, 0.0041,
        0.005 ],
       [0.0024, 0.0319, 0.0024, ..., 0.0026, 0.0478,
        0.0053],
       [0.0169, 0.0068, 0.0007, ..., 0.0554, 0.0028,
        0.0058],
       ...,
       [0.0133, 0.0205, 0.0323, ..., 0.0177, 0.0067,
        0.0155],
       [0.0139, 0.0025, 0.0025, ..., 0.0163, 0.0034,
        0.0107],
       [0.0867, 0.0364, 0.0067, ..., 0.0119, 0.0352,
        0.0038]])

In [20]:
y2

array([[0.0073, 0.015 , 0.0264, ..., 0.0402, 0.0041,
        0.005 ],
       [0.0024, 0.0319, 0.0024, ..., 0.0026, 0.0478,
        0.0053],
       [0.0169, 0.0068, 0.0007, ..., 0.0554, 0.0028,
        0.0058],
       ...,
       [0.0133, 0.0205, 0.0323, ..., 0.0177, 0.0067,
        0.0155],
       [0.0139, 0.0025, 0.0025, ..., 0.0163, 0.0034,
        0.0107],
       [0.0867, 0.0364, 0.0067, ..., 0.0119, 0.0352,
        0.0038]])

In [21]:
np.max(y1-y2)

1.3877787807814457e-17