In [201]:
import sys
sys.path.append('C:/Users/dinle/Code/Learning/Py_Code/AI_Learning/mnist')
sys.path.append('C:/Users/dinle/Code/Learning/Py_Code/AI_Learning/NodeLayer')
import NodeLayer.Layers.layers as layers
import mnist.common.layers as layers2
import numpy as np


scale = np.sqrt(2.0 / 50)
W = scale * np.random.randn(50, 100)
b = np.ones(100)
x = np.random.randn(128, 50)
gamma = np.ones(100)
beta = np.zeros(100)
t = np.random.randint(0,49,128)

L1 = layers.SoftmaxWithLoss()
L2 = layers2.SoftmaxWithLoss()

W

array([[-0.1122,  0.0619,  0.0655, ..., -0.1985,  0.2643,
         0.2961],
       [-0.0428, -0.1317, -0.2921, ..., -0.2099, -0.0635,
        -0.1829],
       [-0.0328, -0.1979, -0.1487, ...,  0.0223, -0.0477,
        -0.0198],
       ...,
       [ 0.11  ,  0.1005, -0.2511, ..., -0.2969,  0.1257,
        -0.2134],
       [ 0.2309,  0.2484, -0.0395, ...,  0.0091, -0.0245,
        -0.1617],
       [ 0.0544, -0.0995,  0.3328, ...,  0.1687,  0.1581,
         0.1142]])

In [202]:
def softmax(x):
    if x.ndim == 2:
        x = x.T
        x = x - np.max(x, axis=0)
        y = np.exp(x) / np.sum(np.exp(x), axis=0)
        return y.T

    x = x - np.max(x) # 오버플로 대책
    return np.exp(x) / np.sum(np.exp(x))

In [203]:
def softmax2(x):
    if x.ndim == 2:
        x = x.T
        x = x - np.max(x, axis=0)
        a = np.exp(x)
        b = (1/ np.sum(np.exp(x), axis=0))
        y = a*b
        return y.T

    x = x - np.max(x) # 오버플로 대책
    return np.exp(x) / np.sum(np.exp(x))

In [204]:
f1 = L1.forward(x,t)
f2 = L2.forward(x,t)

In [205]:
s1 = softmax(x)

In [206]:
s2 = softmax2(x)

In [207]:
s1

array([[0.0613, 0.0045, 0.0122, ..., 0.0037, 0.0123,
        0.0016],
       [0.0026, 0.0392, 0.0168, ..., 0.0165, 0.0161,
        0.0274],
       [0.0177, 0.008 , 0.0273, ..., 0.0117, 0.0068,
        0.0109],
       ...,
       [0.0156, 0.0091, 0.0093, ..., 0.1259, 0.0035,
        0.0089],
       [0.0067, 0.0554, 0.0225, ..., 0.0163, 0.0119,
        0.0679],
       [0.0265, 0.0803, 0.0356, ..., 0.0124, 0.0397,
        0.0244]])

In [208]:
s2

array([[0.0613, 0.0045, 0.0122, ..., 0.0037, 0.0123,
        0.0016],
       [0.0026, 0.0392, 0.0168, ..., 0.0165, 0.0161,
        0.0274],
       [0.0177, 0.008 , 0.0273, ..., 0.0117, 0.0068,
        0.0109],
       ...,
       [0.0156, 0.0091, 0.0093, ..., 0.1259, 0.0035,
        0.0089],
       [0.0067, 0.0554, 0.0225, ..., 0.0163, 0.0119,
        0.0679],
       [0.0265, 0.0803, 0.0356, ..., 0.0124, 0.0397,
        0.0244]])

In [209]:
np.min(s1/s2)

0.9999999999999998

In [210]:
f1

4.47855677283685

In [211]:
f2

4.47855677283685

In [212]:
ff = f1 - f2
np.max(ff)

0.0

In [213]:
b1 = L1.backward(f1)
b2 = L2.backward(f2)

In [214]:
b1

array([[ 4.7865e-04,  3.5258e-05,  9.5412e-05, ...,
         2.8929e-05,  9.5767e-05,  1.2745e-05],
       [ 2.0562e-05, -7.5063e-03,  1.3163e-04, ...,
         1.2921e-04,  1.2550e-04,  2.1399e-04],
       [ 1.3831e-04,  6.2445e-05,  2.1327e-04, ...,
         9.1178e-05,  5.3171e-05,  8.5003e-05],
       ...,
       [ 1.2197e-04,  7.0946e-05,  7.2909e-05, ...,
         9.8328e-04,  2.7158e-05,  6.9463e-05],
       [ 5.2306e-05,  4.3307e-04,  1.7565e-04, ...,
         1.2762e-04,  9.3314e-05,  5.3062e-04],
       [ 2.0725e-04,  6.2757e-04,  2.7779e-04, ...,
         9.7052e-05,  3.1002e-04,  1.9035e-04]])

In [215]:
b2

array([[ 4.7865e-04,  3.5258e-05,  9.5412e-05, ...,
         2.8929e-05,  9.5767e-05,  1.2745e-05],
       [ 2.0562e-05, -7.5063e-03,  1.3163e-04, ...,
         1.2921e-04,  1.2550e-04,  2.1399e-04],
       [ 1.3831e-04,  6.2445e-05,  2.1327e-04, ...,
         9.1178e-05,  5.3171e-05,  8.5003e-05],
       ...,
       [ 1.2197e-04,  7.0946e-05,  7.2909e-05, ...,
         9.8328e-04,  2.7158e-05,  6.9463e-05],
       [ 5.2306e-05,  4.3307e-04,  1.7565e-04, ...,
         1.2762e-04,  9.3314e-05,  5.3062e-04],
       [ 2.0725e-04,  6.2757e-04,  2.7779e-04, ...,
         9.7052e-05,  3.1002e-04,  1.9035e-04]])

In [216]:
bb = b1-b2
np.max(bb)

8.673617379884035e-19

In [217]:
# dw = L1.dW - L2.dW
# np.max(dw)

In [218]:
y1 = L1.y
y2 = L2.y

In [219]:
y1

array([[0.0613, 0.0045, 0.0122, ..., 0.0037, 0.0123,
        0.0016],
       [0.0026, 0.0392, 0.0168, ..., 0.0165, 0.0161,
        0.0274],
       [0.0177, 0.008 , 0.0273, ..., 0.0117, 0.0068,
        0.0109],
       ...,
       [0.0156, 0.0091, 0.0093, ..., 0.1259, 0.0035,
        0.0089],
       [0.0067, 0.0554, 0.0225, ..., 0.0163, 0.0119,
        0.0679],
       [0.0265, 0.0803, 0.0356, ..., 0.0124, 0.0397,
        0.0244]])

In [220]:
y2

array([[0.0613, 0.0045, 0.0122, ..., 0.0037, 0.0123,
        0.0016],
       [0.0026, 0.0392, 0.0168, ..., 0.0165, 0.0161,
        0.0274],
       [0.0177, 0.008 , 0.0273, ..., 0.0117, 0.0068,
        0.0109],
       ...,
       [0.0156, 0.0091, 0.0093, ..., 0.1259, 0.0035,
        0.0089],
       [0.0067, 0.0554, 0.0225, ..., 0.0163, 0.0119,
        0.0679],
       [0.0265, 0.0803, 0.0356, ..., 0.0124, 0.0397,
        0.0244]])

In [221]:
np.max(y1-y2)

2.7755575615628914e-17