In [1]:
import sys
sys.path.append('C:/Users/dinle/Code/Learning/Py_Code/AI_Learning/mnist')
sys.path.append('C:/Users/dinle/Code/Learning/Py_Code/AI_Learning/NodeLayer')
import numpy as np
import matplotlib.pyplot as plt
from mnist.dataset.mnist import load_mnist
from mnist.common.util import smooth_curve
from mnist.common.optimizer import *
from NodeLayer.Networks.multi_layer_net_extend import MultiLayerNetExtend as MLE1
from mnist.common.multi_layer_net_extend import MultiLayerNetExtend as MLE2

In [2]:
networks1 = MLE1(input_size=784, hidden_size_list=[100, 100, 100, 100, 100], output_size=10,
                                weight_init_std=0.293)
networks2 = MLE2(input_size=784, hidden_size_list=[100, 100, 100, 100, 100], output_size=10,
                                weight_init_std=0.293)

In [3]:
(x_train, t_train), (x_test, t_test) = load_mnist(normalize=True)

# 학습 데이터를 줄임
x_train = x_train[:1000]
t_train = t_train[:1000]

max_epochs = 20
train_size = x_train.shape[0]
batch_size = 100
learning_rate = 0.01


In [4]:
train_acc_list = []
bn_train_acc_list = []

iter_per_epoch = max(train_size / batch_size, 1)
epoch_cnt = 0


In [5]:
for k in networks1.params.keys():
    for i in range(networks1.params[k].shape[0]):
        networks1.params[k][i] = networks2.params[k][i].copy()

In [6]:
batch_mask = np.random.choice(train_size, batch_size)
x_batch = x_train[batch_mask]
t_batch = t_train[batch_mask]

pred1 = networks1.predict(x_batch)
pred2 = networks2.predict(x_batch)
y1 = networks1.last_layer.forward(pred1, t_batch)
y2 = networks2.last_layer.forward(pred1, t_batch)
dy1 = networks1.last_layer.backward(1)
dy2 = networks2.last_layer.backward(1)

grads1 = networks1.gradient(x_batch, t_batch)
grads2 = networks2.gradient(x_batch, t_batch)


In [7]:
t = networks1.last_layer.t
y = networks1.last_layer.y
y * t

array([[0.0000e+000, 0.0000e+000, 3.0859e-001,
        0.0000e+000, 0.0000e+000, 0.0000e+000,
        0.0000e+000, 0.0000e+000, 0.0000e+000,
        0.0000e+000],
       [0.0000e+000, 0.0000e+000, 0.0000e+000,
        0.0000e+000, 0.0000e+000, 0.0000e+000,
        0.0000e+000, 1.3382e-138, 0.0000e+000,
        0.0000e+000],
       [0.0000e+000, 0.0000e+000, 0.0000e+000,
        0.0000e+000, 0.0000e+000, 1.8470e-143,
        0.0000e+000, 0.0000e+000, 0.0000e+000,
        0.0000e+000],
       [0.0000e+000, 0.0000e+000, 0.0000e+000,
        0.0000e+000, 1.8593e-140, 0.0000e+000,
        0.0000e+000, 0.0000e+000, 0.0000e+000,
        0.0000e+000],
       [0.0000e+000, 0.0000e+000, 0.0000e+000,
        0.0000e+000, 0.0000e+000, 0.0000e+000,
        0.0000e+000, 2.8924e-148, 0.0000e+000,
        0.0000e+000],
       [0.0000e+000, 0.0000e+000, 1.1144e-008,
        0.0000e+000, 0.0000e+000, 0.0000e+000,
        0.0000e+000, 0.0000e+000, 0.0000e+000,
        0.0000e+000],
       [0.0000e+000, 0

In [8]:
np.max(pred1 - pred2)

0.0

In [9]:
np.max(y1-y2)

0.0

In [10]:
y1/y2

1.0

In [11]:
dy1 -dy2

array([[-4.4842e-044,  0.0000e+000,  0.0000e+000,
         0.0000e+000,  0.0000e+000,  0.0000e+000,
         0.0000e+000,  0.0000e+000, -8.3524e-053,
        -3.4099e-254],
       [ 0.0000e+000,  0.0000e+000,  0.0000e+000,
         0.0000e+000,  0.0000e+000,  5.6354e-132,
         2.1801e-106,  0.0000e+000,  0.0000e+000,
         0.0000e+000],
       [ 0.0000e+000,  0.0000e+000,  0.0000e+000,
         0.0000e+000,  0.0000e+000,  0.0000e+000,
         0.0000e+000,  0.0000e+000,  0.0000e+000,
         0.0000e+000],
       [ 0.0000e+000,  0.0000e+000,  0.0000e+000,
         0.0000e+000,  0.0000e+000,  0.0000e+000,
         0.0000e+000,  0.0000e+000,  0.0000e+000,
         0.0000e+000],
       [ 0.0000e+000,  0.0000e+000,  0.0000e+000,
         0.0000e+000,  0.0000e+000,  0.0000e+000,
         0.0000e+000,  0.0000e+000,  0.0000e+000,
         0.0000e+000],
       [ 0.0000e+000,  0.0000e+000,  0.0000e+000,
         0.0000e+000,  0.0000e+000,  0.0000e+000,
         0.0000e+000,  0.0000e+000,

In [12]:
dy1 / dy2

C:\Users\dinle\AppData\Local\Temp\ipykernel_10800\4074325240.py:1: RuntimeWarning: invalid value encountered in divide
  dy1 / dy2


array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1., nan,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.

In [13]:
print(np.max(dy1-dy2))

4.336808689942018e-19


In [14]:
c1 = networks1